stages:
  - docker-ci
  - testing
  - laravel
dockerupload:
  image: docker:20.10.16
  stage: docker-ci
  services:
    - docker:20.10.16-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
  - docker build -t $CI_REGISTRY_IMAGE  .
  - docker images
  - docker push $CI_REGISTRY_IMAGE
