stages:
  - testing
  - laravel

phpcompile:
  image: php
  stage: testing
  script:
    - php --version
laravelCompile:
  image: php:8.0
  stage: laravel
  script:
    - apt-get update && apt-get install -qy git zip curl libmcrypt-dev default-mysql-client libxml2-dev default-jre wget maven
    - yes | pecl install mcrypt
    - docker-php-ext-install pdo_mysql bcmath
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - ln -f -s .env.pipelines .env
    - php artisan migrate
    - php artisan serve &
    - sleep 5
    - ./vendor/bin/phpunit
    - curl -vk http://localhost:8000


