image: docker:20.10.16

pipelines:
  branches:
    '**':
      - step:
          name: Docker Build and Push
          script:
            - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
            - docker build -t $CI_REGISTRY_IMAGE .
            - docker images
            - docker push $CI_REGISTRY_IMAGE
          services:
            - docker
          
