image: docker:latest

pipelines:
  branches:
    '**':
    - step:
        trigger: 'automatic'
        name: Docker Build and Deploy
        script:
        - docker login -u $CI_REGISTER_USER$CI_REGISTRY --password $CI_REGISTRY_PASSWORD
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker images
        - docker push $CI_REGISTRY_IMAGE